apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kisan-dr-ai-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "kisan-static-ip"
    networking.gke.io/managed-certificates: "kisan-ssl-cert"
spec:
  rules:
    - http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: kisan-dr-ai-service
                port:
                  number: 80
