apiVersion: v1
kind: Service
metadata:
  name: kisan-dr-ai-service
  namespace: default
  labels:
    app: kisan-dr-ai
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
      name: http
    - port: 50051
      targetPort: 50051
      name: grpc
  selector:
    app: kisan-dr-ai
